<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset=utf-8>
    <title>Error 404 - <?= APP_NAME; ?></title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="robots" content="noindex,nofollow" />
    <link rel="shortcut icon" href="<?= PUBLIC_PATH; ?>favicon.ico" type="image/x-icon" />
    <style>
        body{
            font-family:arial;
            text-align: center;
            background:#eeeeee none repeat scroll 0 0;
        }
        img {
            border: 0;
            max-width: 200px;;
            height: auto;
            margin-top: 100px;
        }
        .logo {
            padding:0
        }
        #error-404{
            padding-top:2%
        }
        p {
            font-size: 1.5rem;
        }
        h1 {
            color: #FE4747;
            font-size: 5rem;
            line-height: 0;
            font-family:"arial black";
            margin-top: 100px;
        }
        .logo {
            background:transparent
        }
        .logo:hover {
            border:none
        }
        a {
            color:#fff;
            background:#00A1CB;
            padding:.5em 2em;
            border-radius:2em;
            margin-top:1em;
            font-size:large;
            font-weight: bold;
            text-decoration:none
        }
        a:hover{
            background:#eee;
            border:2px solid #00A1CB;
            color:#00A1CB;
        }
    </style>
</head>
<body>
    <div id="error-404">
        <h1>404</h1>
        <p>¡Oops! Este recurso no está disponible por el momento.</p>
        <a class=logo href="http://www.kumbiaphp.com" title="Web de KumbiaPHP Framework">
            <img src="<?= PUBLIC_PATH; ?>img/logo.png" alt="Dailyscript - Web | Apps"/>
        </a>
    </div>
</body>
</html>
