<?php

/**
 * Capturo las variables a utilizar
 */
$data = $data['data'];

DwExcel::create('Reporte de Usuarios', function($excel) use ($data) {

    $excel->sheet('Usuarios', function($sheet) use($data) {

        $sheet->setOrientation(DwExcel::LANDSCAPE);

        $cont = 1;

        //primera linea, titulos del excel
        $sheet->setCell("A$cont", 'Num', DwExcel::BOLD);
        $sheet->setCell("B$cont", 'Nombre', DwExcel::BOLD);
        $sheet->setCell("C$cont", 'Email', DwExcel::BOLD);
        $sheet->setCell("D$cont", 'Fecha de Ingreso', DwExcel::BOLD);
        $sheet->setCell("E$cont", 'Estado', DwExcel::BOLD);

        $cont++;

        foreach ($data as $usuario) {

            $sheet->setCell("A$cont", ($cont - 1));
            $sheet->setCell("B$cont", $usuario->nombre);
            $sheet->setCell("C$cont", $usuario->email);
            $sheet->setCell("D$cont", $usuario->usuario_at);
            $sheet->setCell("E$cont", $usuario->estado ? 'ACTIVO' : 'INACTIVO');

            $cont++;
        }

    });

})->export('xls');

