<div class="view-login">

    <div class="row align-center">
        <div class="small-11 columns">

                <form action="" method="post" class="form-login" data-abide novalidate>

                    <div class="row align-center">
                        <div class="small-11 columns text-center">
                            <img src="img/logo.png" alt="KumbiaPHP Project" class="logo-login">
                        </div>
                    </div>

                    <div class="row align-center">
                        <div class="small-11 columns">
                            <label>Email
                                <input type="email" name="email" required pattern="email">
                                <small class="form-error">Ingresa tu email</small>
                            </label>
                        </div>
                    </div>

                    <div class="row align-center">
                        <div class="small-11 columns">
                            <label>Password
                                <input type="password" name="password" required>
                                <small class="form-error">Ingresa tu contraseña</small>
                            </label>
                        </div>
                    </div>

                    <div class="row align-center">
                        <div class="small-11 columns text-right">
                            <button class="button primary" type="submit">Entrar</button>
                        </div>
                    </div>

                </form>

        </div>
    </div>

</div>
