<div class="view-home">

    <div class="row align-center stats-content">

        <div class="small-6 columns text-left stats-content__counter">
            <ul class="inline menu no-bullet">
                <li class="text-center">
                    <b>0</b>
                    <p>Total</p>
                </li>
            </ul>
        </div>

        <div class="small-6 columns text-right stats-content__export">
            <a href="#" class="button terciary button--add"><i class="mdi mdi-plus"></i> Agregar</a>
            <a href="#" class="button primary button--download"><i class="mdi mdi-download"></i> Exportar</a>
        </div>

    </div>

    <div class="row align-center">
        <div class="small-12 columns">
            <div class="card">
                <table>
                    <thead class="wrap-table__head">
                        <tr>
                            <th class="small-1 text-center">#</th>
                            <th class="small-4">Nombre</th>
                            <th class="small-3">Email</th>
                            <th class="small-2">Estado</th>
                            <th class="small-2"></th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>

</div>
